name: Build

on:
  push:
    paths-ignore: ['*.md']
  pull_request:
    paths-ignore: [ '*.md' ]
    branches: [ master ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Cache composer dependencies
        uses: actions/cache@v2
        env:
          cache-name: laravel-cloudflare-analysis
        with:
          path: ~/.composer
          key: php-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php }}-build-${{ env.cache-name }}-
            php-${{ matrix.php }}-build-
            php-${{ matrix.php }}-
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run phpstan analysis
        run: composer phpstan-analysis
      - name: Run phpmd analysis
        run: composer phpmd-analysis
      - name: Run phpcpd analysis
        run: vendor/bin/phpcpd --min-lines=3 --min-tokens=36 src/
  laravel8:
    needs: [analysis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Force update laravel version
        run: composer require "laravel/framework:^8.0" "orchestra/testbench:^6.0" --no-update
      - name: Remove some dev dependencies
        run: composer remove "ekino/phpstan-banned-code" "nunomaduro/larastan" "phpmd/phpmd" "phpstan/phpstan-deprecation-rules" "sebastian/phpcpd" --dev --no-update
      - name: Cache composer dependencies
        uses: actions/cache@v2
        env:
          cache-name: laravel-cloudflare-laravel8
        with:
          path: ~/.composer
          key: php-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php }}-build-${{ env.cache-name }}-
            php-${{ matrix.php }}-build-
            php-${{ matrix.php }}-
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run the test suite
        run: phpdbg -qrr -dmemory_limit=3G vendor/bin/phpunit
  laravel9:
    needs: [ analysis ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 8.1, 8.2 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Force update laravel version
        run: composer require "laravel/framework:^9.0" "orchestra/testbench:^7.0" --no-update
      - name: Remove some dev dependencies
        run: composer remove "ekino/phpstan-banned-code" "nunomaduro/larastan" "phpmd/phpmd" "phpstan/phpstan-deprecation-rules" "sebastian/phpcpd" "orchestra/database" --dev --no-update
      - name: Cache composer dependencies
        uses: actions/cache@v2
        env:
          cache-name: laravel-cloudflare-laravel9
        with:
          path: ~/.composer
          key: php-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php }}-build-${{ env.cache-name }}-
            php-${{ matrix.php }}-build-
            php-${{ matrix.php }}-
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run the test suite
        run: phpdbg -qrr -dmemory_limit=3G vendor/bin/phpunit
  laravel10:
    needs: [ analysis ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.1 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Force update laravel version
        run: composer require "laravel/framework:^10.0" "orchestra/testbench:^8.0" --no-update
      - name: Remove some dev dependencies
        run: composer remove "ekino/phpstan-banned-code" "nunomaduro/larastan" "phpmd/phpmd" "phpstan/phpstan-deprecation-rules" "sebastian/phpcpd" "orchestra/database" --dev --no-update
      - name: Cache composer dependencies
        uses: actions/cache@v2
        env:
          cache-name: laravel-cloudflare-laravel10
        with:
          path: ~/.composer
          key: php-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php }}-build-${{ env.cache-name }}-
            php-${{ matrix.php }}-build-
            php-${{ matrix.php }}-
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run the test suite
        run: phpdbg -qrr -dmemory_limit=3G vendor/bin/phpunit
  laravel10-cov:
    needs: [analysis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Force update laravel version
        run: composer require "laravel/framework:^10.0" "orchestra/testbench:^8.0" --no-update
      - name: Cache composer dependencies
        uses: actions/cache@v2
        env:
          cache-name: laravel-cloudflare-laravel10-cov
        with:
          path: ~/.composer
          key: php-${{ matrix.php }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php }}-build-${{ env.cache-name }}-
            php-${{ matrix.php }}-build-
            php-${{ matrix.php }}-
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run the Coverage test suite
        run: phpdbg -qrr -dmemory_limit=3G vendor/bin/phpunit --coverage-clover=clover.xml
      - name: Upload test coverage report to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
